name: krok
description: Kraken API plus command line client for Dart.
version: 0.0.1
repository: https://github.com/DanielLukic/dart-kraken-api
topics: [ kraken, api, client, dart ]

environment:
  sdk: ^3.3.1

dependencies:
  ansi: ^0.4.2
  args: ^2.4.2
  cli_util: ^0.4.1
  crypto: ^3.0.1
  http: ^1.2.1
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
