name: krok
description: Kraken Crypto API plus command line client for Dart. Inspired by the python clikraken tool.
homepage: https://github.com/DanielLukic/krok-dart
repository: https://github.com/DanielLukic/krok-dart
topics: [ kraken, api, client, dart ]
version: 0.0.5

environment:
  sdk: ^3.3.1

dependencies:
  ansi: ^0.4.2
  args: ^2.4.2
  cli_util: ^0.4.1
  crypto: ^3.0.1
  http: ^1.2.1
  dart_minilog: ^0.0.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
